USE recycling_hiring;

INSERT INTO candidates (full_name, experience_years, skills) VALUES
('Dominic Marquardt', 15, '["Recycling Operations","Process Optimization","Environmental Law","Team Handling","Safety Compliance"]'),
('Ignacio Harris', 7, '["Environmental Law","Safety Compliance","Waste Management","Process Optimization"]'),
('Lela Feil', 15, '["Safety Compliance","Sustainability","Process Optimization","Environmental Law"]'),
('Matthew Dooley', 7, '["Team Handling","Waste Management","Environmental Law","Sustainability"]'),
('Toby Volkman', 16, '["Process Optimization","Recycling Operations","Waste Management"]'),
('Carlton Hartmann', 9, '["Leadership","Team Handling","Waste Management","Process Optimization"]'),
('Salvador Towne', 2, '["Sustainability","Safety Compliance","Leadership"]'),
('Mr. Glenn VonRueden', 15, '["Process Optimization","Team Handling","Environmental Law"]'),
('Marty Hilll Sr.', 15, '["Process Optimization","Waste Management","Safety Compliance"]'),
('Donna Muller', 19, '["Waste Management","Environmental Law","Leadership"]'),
('Robyn Pfeffer', 16, '["Recycling Operations","Safety Compliance","Process Optimization"]'),
('Shawna Hegmann', 9, '["Leadership","Recycling Operations","Safety Compliance","Team Handling"]'),
('Nadine Klein', 2, '["Team Handling","Leadership","Sustainability","Process Optimization"]'),
('Lana Brown', 15, '["Sustainability","Process Optimization","Waste Management","Environmental Law","Recycling Operations"]'),
('Angel Wiza Jr.', 19, '["Environmental Law","Process Optimization","Safety Compliance","Waste Management"]'),
('Casey Koepp', 15, '["Waste Management","Process Optimization","Sustainability"]'),
('Christine Ferry', 10, '["Waste Management","Environmental Law","Leadership","Safety Compliance"]'),
('Juanita King', 7, '["Process Optimization","Team Handling","Recycling Operations","Sustainability","Environmental Law"]'),
('Delores Gutmann', 14, '["Recycling Operations","Safety Compliance","Process Optimization","Environmental Law","Waste Management"]'),
('Jamie Wuckert', 20, '["Process Optimization","Sustainability","Safety Compliance","Environmental Law"]'),
('Jaime Walker', 2, '["Recycling Operations","Environmental Law","Safety Compliance"]'),
('Erick Wintheiser', 1, '["Sustainability","Process Optimization","Environmental Law","Waste Management","Team Handling"]'),
('Miss Ramona Stanton III', 16, '["Recycling Operations","Waste Management","Safety Compliance"]'),
('Sheri Gottlieb', 19, '["Leadership","Environmental Law","Process Optimization"]'),
('Eduardo Huels III', 1, '["Sustainability","Recycling Operations","Leadership","Team Handling","Environmental Law"]'),
('Brian Auer', 18, '["Process Optimization","Sustainability","Environmental Law","Leadership","Team Handling"]'),
('Leonard Jacobs', 2, '["Leadership","Waste Management","Process Optimization","Environmental Law"]'),
('Perry Powlowski', 16, '["Leadership","Recycling Operations","Process Optimization","Team Handling"]'),
('Jeffrey Rath', 3, '["Leadership","Sustainability","Team Handling","Safety Compliance","Process Optimization"]'),
('Ms. Patricia Tromp', 4, '["Team Handling","Safety Compliance","Process Optimization","Waste Management","Leadership"]'),
('Dr. Carroll Wisoky', 8, '["Waste Management","Team Handling","Environmental Law","Safety Compliance"]'),
('Dr. Helen Grant', 8, '["Recycling Operations","Environmental Law","Process Optimization"]'),
('Glenn Cruickshank', 20, '["Process Optimization","Leadership","Environmental Law","Recycling Operations"]'),
('Kathleen Weissnat', 9, '["Safety Compliance","Team Handling","Process Optimization"]'),
('Penny Mueller', 14, '["Team Handling","Environmental Law","Process Optimization","Waste Management"]'),
('Dr. Chris Braun', 17, '["Process Optimization","Waste Management","Team Handling","Safety Compliance"]'),
('Santos O'Connell', 13, '["Safety Compliance","Sustainability","Leadership","Environmental Law"]'),
('Julia Stamm', 14, '["Recycling Operations","Waste Management","Sustainability","Process Optimization"]'),
('Archie Gutkowski-Lubowitz', 11, '["Environmental Law","Process Optimization","Leadership","Team Handling","Sustainability"]'),
('Hannah Anderson', 14, '["Environmental Law","Sustainability","Leadership"]');
